name = "Hexxy 4"
author = "Chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffd9cb6a078e03fc9b8755d0bd1cb5fec2d00ce64f9454761afd65ab515f661f"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
no-internal-hashes = true
