name = "Hexxy 4"
author = "Chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a390741cfc194fc1f125ef5d1b52b526f6ddc71c29dfb75cb655368606192f0d"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
no-internal-hashes = true
